
data4 <- read.table("data/household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
data4 <- data4[data4$Date %in% c("1/2/2007","2/2/2007") ,]
datetime <- strptime(paste(data4$Date, data4$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
gap <- as.numeric(data4$Global_active_power)
grp <- as.numeric(data4$Global_reactive_power)
voltage <- as.numeric(data4$Voltage)
SM1 <- as.numeric(data4$Sub_metering_1)
SM2 <- as.numeric(data4$Sub_metering_2)
SM3 <- as.numeric(data4$Sub_metering_3)
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2)) 
plot(datetime, gap, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(datetime, voltage, type="l", xlab="datetime", ylab="Voltage")
plot(datetime, SM1, type="l", ylab="Energy Submetering", xlab="")
lines(datetime, SM2, type="l", col="red")
lines(datetime, SM3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(datetime, grp, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()

